//list of all image path

const String notificationIcon = "assets/images/notification.svg";
const String walletPic = 'assets/images/wal.png';
const String physicsPic = "assets/homework.png";
const String feedbackImg = "assets/feedBack.png";
const String mathsPic = "assets/images/maths.png";
const String sciencePic = "assets/images/sciencePic.png";
const String biologyPic = "assets/images/biologyPic.png";
const String mathematicsPic = "assets/images/mathematicsPic.png";
const String openLessonBg = "assets/images/openLessonBg.png";
const String studentPic = "assets/images/studentPic.png";
const String mathBanner = "assets/images/MathBanner.png";
const String englishBanner1 = "assets/images/EnglishBanner1.png";
const String englishBanner2 = "assets/images/EnglishBanner2.png";
const String scienceBanner = "assets/images/ScienceBanner.png";
const String happyEmoji = "assets/images/happyEmoji.png";
const String sadEmoji = "assets/images/sadEmoji.png";
const String hw2 = "assets/images/hw2.png";
